ShoppingList/Controllers/DishesController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using ShoppingList.Core.Abstractions;
using ShoppingList.Core.Models;
using ShoppingList.Shared.Models;
using ShoppingList.Web.Models;
using ShoppingList.Web.Models.Views;

namespace ShoppingList.Web.Controllers
{
    public class DishesController : Controller
    {
        private readonly IDishesService _service;
        private readonly IShoppingListItemsService _ingredients;

        public DishesController(IDishesService service, IShoppingListItemsService ingredients)
        {
            _service = service;
            _ingredients = ingredients;
        }

        public async Task<IActionResult> Index(CancellationToken token)
        {
            var dishes = await _service.All(0, 500, token);
            if (dishes.Status == ResultStatus.Ok)
            {
                return View(dishes.Result);
            }
            return View(new List<Dish>());
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(DishCreation dish, CancellationToken token)
        {
            var ingredients = await _ingredients.GetByIds(dish.Ingredients, token);

            if (ingredients.Status == ResultStatus.Ok && 
                dish.FeaturedImage != null && dish.FeaturedImage.IsImage() && dish.FeaturedImage.Length < 8388608) //allow 8mb
            {
                CoreResult<Dish> result;
                await using (var memoryStream = new MemoryStream())
                {
                    await dish.FeaturedImage.CopyToAsync(memoryStream, token);
                    result = await _service.Create(new Dish
                    {
                        Id = dish.Id,
                        FeaturedImage = memoryStream.ToArray(),
                        HowTo = dish.HowTo,
                        Ingredients = ingredients.Result,
                        Name = dish.Name
                    }, token);
                }

                if (result.Status == ResultStatus.Ok)
                {
                    foreach (var ingredient in ingredients.Result)
                    {
                        ingredient.Dish = result.Result;
                        await _ingredients.Set(ingredient, token);
                    }

                    return RedirectToAction("Index");
                }
            }

            return View(dish); //try again 
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            return View();
        }

        [HttpPost]
        public IActionResult Edit(int id, Dish dish, CancellationToken token)
        {
            return View();
        }

        public IActionResult Details()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id, CancellationToken token)
        {
            await _service.Remove(id, token);
            return RedirectToAction("Index");
        }
    }
}

ShoppingList/Controllers/ShoppingListItemsController.cs
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ShoppingList.Core.Abstractions;
using ShoppingList.Shared.Models;

namespace ShoppingList.Web.Controllers
{
    public class ShoppingListItemsController : Controller
    {
        private readonly IShoppingListItemsService _shoppingListItemsService;

        public ShoppingListItemsController(IShoppingListItemsService shoppingListItemsService)
        {
            _shoppingListItemsService = shoppingListItemsService;
        }

        public async Task<IActionResult> Index(CancellationToken token)
        {
            var items = await _shoppingListItemsService.AllOrphaned(0, 500, token);
            if (items.Status == ResultStatus.Ok)
            {
                return View(items.Result);
            }

            return View(new List<ShoppingListItem>());
        }

        [HttpGet]
        public async Task<IActionResult> Details(int id, CancellationToken token)
        {
            var item = await _shoppingListItemsService.GetById(id, token);
            if (item.Status == ResultStatus.Ok)
            {
                return View(item.Result);
            }

            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id, CancellationToken token)
        {
            var item = await _shoppingListItemsService.GetById(id, token);

            if (item.Status == ResultStatus.Ok)
            {
                return View(item.Result);
            }

            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> Edit(ShoppingListItem item, CancellationToken token)
        {
            var result = await _shoppingListItemsService.Set(item, token);
            if (result.Status == ResultStatus.Ok)
            {
                return RedirectToAction("Details", new {id = item.Id});
            }

            return View(item);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }


        [HttpPost]
        public async Task<IActionResult> Create(ShoppingListItem item, CancellationToken token)
        {
            var result = await _shoppingListItemsService.Create(item, token);
            if (result.Status == ResultStatus.Ok)
            {
                return RedirectToAction("Details", new {id = item.Id});
            }

            return View();
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id, CancellationToken token)
        {
            await _shoppingListItemsService.Remove(id, token);
            return RedirectToAction("Index");
        }
    }
}

ShoppingList/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - ShoppingList</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/lib/bootstrap-dark/dist/css/bootstrap-dark.min.css"/>
    <link rel="stylesheet" href="~/css/site.css"/>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm  border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ShoppingList</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Dishes" asp-action="Index">Dishes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="ShoppingListItems" asp-action="Index">Ingredients</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
            <div id="modal" class="modal fade" tabindex="-1" role="dialog" style="display: none;">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title">Modal title</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                        </div>
                        <div class="modal-footer">
                            <button type="button" id="button1" class="btn btn-primary">Save changes</button>
                            <button type="button" id="button2" class="btn btn-secondary">Close</button>
                        </div>
                    </div>
                </div>
            </div>
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - ShoppingList - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

  
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>